### ISSUE TITLE
Doesn't run on Raspberry pi install of HA

### ISSUE THREAD

**Issue by General1337** [Tediore/audioflow2mqtt#11]
Hi, 
When trying to run this on a home assistant install on Raspberry pi I am given this error message:

"[Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested"

I'm unable to run this on Pi 4.

**Comment by Tediore** [comment]
Sorry about that. Try pulling and running the image again--it should work now.

**Comment by Tediore** [comment]
Closed as I confirmed it works on a raspberry pi of my own. Feel free to comment if you're still having issues
