### ISSUE TITLE
Blocking Strategy

### ISSUE THREAD

**Issue by iamlazarus** [Tediore/audioflow2mqtt#12]
According to Wikipedia ProtonVPN has 1500 servers in 61 countries, blocking all of them will almost certainly create collateral damage and affect other users, but hey if that's your plan. I'm going to start with big west coast metros first and then move to the biggest populations centers working my way down.

Seems like an awful lot of trouble to go through to keep one person out, and personally I've never gotten the entire network of a multi-national organization blocked before, so ACHIEVEMENT UNLOCKED!

**Comment by Tediore** [comment]
You've got serious issues, dude 🤣
