### ISSUE TITLE
Home assistant - Hacs Custom Intergration

### ISSUE THREAD

**Issue by LRG-Pasty** [Tediore/audioflow2mqtt#20]
Not sure if this is the intended installation method through Home Assistant HACS, hopefully you can let me know 

Hacs 
Custom Integration, when trying the download the following error comes up
<Integration Tediore/audioflow2mqtt> Repository structure for 0.7.0 is not compliant

**Comment by Tediore** [comment]
This isn't a custom integration, so you won't be able to install it via HACS. Installation instructions are in the readme, or I have an add-on version [here](https://github.com/Tediore/audioflow2mqtt-addon) which might be closer to what you're looking for.
